name: Run Python Tests

on: [push, pull_request]  # Run tests when pushing or making a pull request

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu as the test environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clone the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"  # Change to your Python version if needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No dependencies file found"

      - name: Run Tests
        run: python -m unittest discover
