name: Run Python Tests

on: [push, pull_request]  # Run tests on every push and pull request

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu as the test environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clone the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"  # Make sure this matches your local version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: python -m unittest discover

