name: Security Scan

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Security Tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit

      - name: Upgrade Vulnerable Dependencies
        run: |
          pip-audit --fix

      - name: Run Dependency Audit
        run: pip-audit

      - name: Run Code Security Scan
        run: bandit -r .

      - name: Run Secret Scan
        run: ./gitleaks detect
